ErrorSave/ErrorSave/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('error_manage_system.urls')),
    path('email/', include('sendEmail.urls'), name='email'),
]

ErrorSave/error_manage_system/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('loggingError/', views.loggingError, name='logging_error'),
    path('myError/', views.myError, name='my_error'),
    path('loggingError/createError/', views.createError, name='createError'),
    path('<int:e_id>/deleteError/', views.deleteError, name='deleteError'),

    path('<int:e_id>/myDetailError/', views.myDetailError, name='myDetailError'),
    path('<int:e_id>/myDetailError/updateError/', views.update_error, name='updateError'),

    path('<int:e_id>/detailError/', views.detailError, name='detailError'),
    path('<int:e_id>/detailError/loggingSolution/', views.logging_solution, name='logging_solution'),
    path('<int:e_id>/detailError/loggingSolution/createSolution/', views.createSolution, name='createSolution'),

    path('signin/signup/', views.signup, name='main_signup'),
    path('signin/', views.signin, name='main_signin'),
    path('verifyCode/', views.verifyCode, name='main_verifyCode'),
    path('verifyCode/verify/', views.verify, name='main_verify'),

    path('join', views.join, name='main_join'),
    path('signin/signin/login', views.login, name='main_login'),
    path('logout/', views.logout, name='main_logout'),

    path('search_title/', views.search_title, name='serch_title'),
]

ErrorSave/error_manage_system/models.py
from django.db import models


class Error(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=225)
    message = models.TextField()
    code = models.TextField()
    status = models.BooleanField()
    description = models.TextField()


class User(models.Model):
    objects = models.Manager()
    user_name = models.CharField(max_length=20)
    user_email = models.EmailField(unique=True)
    user_password = models.CharField(max_length=100)
    user_validate = models.BooleanField(default=False)


class Match(models.Model):
    objects = models.Manager()
    error_id = models.IntegerField()
    user_id = models.IntegerField()


class Solution(models.Model):
    objects = models.Manager()
    solution_code = models.TextField()
    solution_description = models.TextField()
    user_id = models.IntegerField()
    error_id = models.IntegerField()

ErrorSave/error_manage_system/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Error, User, Match, Solution
from django.urls import reverse
from random import randint
from sendEmail.views import send
from django.contrib import messages
from django.contrib import auth


# 회원가입 화면 랜더링
def signup(request):
    return render(request, 'error_manage_system/signup_init.html')

# 회원가입 로직
def join(request):
    print(request)
    name = request.POST['signupName']
    email = request.POST['signupEmail']
    pw = request.POST['signupPW']
    user = User(user_name=name, user_email=email, user_password=pw)
    user.save()
    code = randint(1000, 9999)
    response = redirect('main_verifyCode')
    response.set_cookie('code', code)
    response.set_cookie('user_id', user.id)
    # 이메일 발송 함수 호출
    send_result = send(email, code)
    if send_result:
        return response
    else:
        return HttpResponse("이메일 발송에 실패했습니다.")

# 인증코드 입력 화면 랜더링
def verifyCode(request):
    return render(request, 'error_manage_system/verifyCode_init.html')

# 인증 로직
def verify(request):
    user_code = request.POST['verifyCode']
    cookie_code = request.COOKIES.get('code')
    if user_code == cookie_code:
        user = User.objects.get(id=request.COOKIES.get('user_id'))
        user.user_validate = 1
        user.save()
        response = redirect('index')
        response.delete_cookie('code')
        response.delete_cookie('user_id')
        # response.set_cookie('user', user)
        request.session['user_name']=user.user_name
        request.session['user_email']=user.user_email
        return response
    else:
        redirect('main_varifyCode')

# 로그인 화면 랜더링
def signin(request):
    return render(request, 'error_manage_system/signin_init.html')

# 로그인 로직
def login(request):
    loginEmail = request.POST.get('loginEmail', None)
    loginPW = request.POST.get('loginPW', None)
    try:
        user = User.objects.get(user_email=loginEmail)
    except:
        return redirect('main_signin')
    if user.user_password == loginPW:
        request.session['user_id'] = user.id
        request.session['user_name'] = user.user_name
        request.session['user_email'] = user.user_email
        return redirect('index')
    else:
        return redirect('main_signin')

# 메인 화면 랜더링 및 에러 기록(게시물) 목록 필터기능 로직
def index(request):
    if 'user_id' in request.session.keys():
        if request.method=="POST":
            status_temp = request.POST.get('Filter')
            if status_temp == 'outstanding':
                status = False
                errors = Error.objects.filter(status=status)
            elif status_temp == 'resolved':
                status = True
                errors = Error.objects.filter(status=status)
            else:
                errors = Error.objects.all()
            content = {"errors": errors, "matchs": Match.objects.all(), "users": User.objects.all()}
            return render(request, 'error_manage_system/index.html', content)

        else:
            errors = Error.objects.all()
            content = {"errors": errors, "matchs": Match.objects.all(), "users": User.objects.all()}
            return render(request, 'error_manage_system/index.html', content)
    else:
        return redirect('main_signin')

# 에러 기록 화면 랜더링
def loggingError(request):
    return render(request, 'error_manage_system/logging_error.html')

# 에러기록 추가 로직
def createError(request):
    errorTitle = request.POST['title']
    errorMessage = request.POST['message']
    errorCode = request.POST['code']
    errorDescription = request.POST['description']
    new_error = Error(title=errorTitle, message=errorMessage, code=errorCode, status=False, description=errorDescription)
    new_error.save()
    
    new_match = Match(user_id=request.session.get('user_id'), error_id=new_error.id)
    new_match.save()
    return HttpResponseRedirect(reverse("index"))

# 제목으로 에러기록 검색 기능 로직
def search_title(request):
    errorTitle = request.POST['errorTitle']
    errors = Error.objects.all()
    search_error = errors.filter(title__contains= errorTitle)
    content = {'search_errors':search_error, "matchs": Match.objects.all(), "users": User.objects.all()}
    return render(request, 'error_manage_system/search_title.html', content)

# 에러 상세정보 기능 로직
def detailError(request, e_id):
    detail_error = Error.objects.get(id=e_id)
    if detail_error.status:
        detail_solution = Solution.objects.get(error_id=e_id)
        content = {"detail_error": detail_error, "detail_solution": detail_solution}
    else:
        content = {"detail_error": detail_error}
    return render(request, 'error_manage_system/detail_error.html', content)

# 솔루션 기록화면 로직
def logging_solution(request, e_id):
    match_error = Error.objects.get(id=e_id)
    content = {"match_error": match_error}
    return render(request, 'error_manage_system/logging_solution.html', content)

# 솔루션 기록 로직
def createSolution(request, e_id):
    match = Match.objects.get(error_id=e_id)
    er_id = match.error_id
    us_id = match.user_id
    # solution 저장
    solutionCode = request.POST['solution_code']
    solutionDescription = request.POST['solution_description']
    new_solution = Solution(solution_code=solutionCode, solution_description=solutionDescription, error_id=er_id, user_id=us_id)
    new_solution.save()
    # error status True
    error_status_up = Error.objects.get(id=er_id)
    error_status_up.status = True
    error_status_up.save()
    return HttpResponseRedirect(reverse("index"))

# 내 에러보기화면 로직
def myError(request):
    id_list = []
    for i in Match.objects.all():
        if i.user_id == request.session.get('user_id'):
            id_list.append(i.error_id)

    if 'user_id' in request.session.keys():
        if request.method=="POST":
            status_temp = request.POST.get('Filter')
            if status_temp == 'outstanding':
                status = False
                errors = Error.objects.filter(status=status)
            elif status_temp == 'resolved':
                status = True
                errors = Error.objects.filter(status=status)
            else:
                errors = Error.objects.all()
            content = {"errors": errors, "id_list": id_list, "user_my": User.objects.get(id=request.session.get('user_id'))}
            return render(request, 'error_manage_system/my_error.html', content)

        else:
            errors = Error.objects.all()
            content = {"errors": errors, "id_list": id_list, "user_my": User.objects.get(id=request.session.get('user_id'))}
            return render(request, 'error_manage_system/my_error.html', content)
    else:
        return redirect('main_signin')

# 내에러 수정기능 화면
def myDetailError(request, e_id):
    detail_error = Error.objects.get(id=e_id)
    if detail_error.status:
        detail_solution = Solution.objects.get(error_id=e_id)
        content = {"detail_error": detail_error, "detail_solution": detail_solution}
    else:
        content = {"detail_error": detail_error}
    return render(request, 'error_manage_system/my_detail_error.html', content)

# 내에러 수정기능 로직
def update_error(request, e_id):
    errorTitle = request.POST['title']
    errorID = request.POST['id']
    errorMessage = request.POST['message']
    errorCode = request.POST['code']
    errorDescription = request.POST['description']
    update_E = Error.objects.get(id=errorID)
    update_E.title = errorTitle
    update_E.message = errorMessage
    update_E.code = errorCode
    update_E.description = errorDescription
    update_E.save()

    solution_status = request.POST['solution_status']
    print(solution_status)
    if solution_status == "1":
        print(solution_status)
        update_S = Solution.objects.get(error_id=errorID)
        solutionCode = request.POST['sol_code']
        solutionDescription = request.POST['sol_description']
        update_S.solution_code = solutionCode
        update_S.solution_description = solutionDescription
        update_S.save()
    return HttpResponseRedirect(reverse("index"))

# 내 에러 기록 삭제 기능 로직
def deleteError(request, e_id):
    delete_match = Match.objects.get(error_id=e_id)
    delete_error = Error.objects.get(id=e_id)
    delete_error.delete()
    delete_match.delete()
    return HttpResponseRedirect(reverse("my_error"))

# 로그아웃 기능 로직
def logout(request):
    del request.session['user_name']
    del request.session['user_email']
    request.session.clear()
    auth.logout(request)
    return redirect('main_signin')

ErrorSave/error_manage_system/templates/error_manage_system/detail_error.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <meta name="description" content>

        <title>Error Save</title>

        <meta name="author" content>
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </head>

    <body>

            <a href="{% url 'index' %}">
                <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
            </a>


            <div style="padding-left:100px;">
                <label class="required">Title:</label>
                <p class="required">{{detail_error.title}}</p>
                <!-- <input type="text" name="title" value={{detail_error.title}} class="vTextField" maxlength="225" id="id_title"> -->
            </div>

            <div style="padding-left:100px; padding-right:100px;" >
                <label class="required" for="id_title">Message:</label>
                <pre class="prettyprint">{{detail_error.message}}</pre>
                <!-- <input type="text" name="message" value={{detail_error.message}} class="vTextField" maxlength="225" id="id_message"> -->
            </div>

            <div style="padding-left:100px; padding-right:100px;">
                <label class="required" for="id_title">Code:</label>
                <pre class="prettyprint">{{detail_error.code}}</pre>
            </div>

            <div style="padding-left:100px;" >
                <label class="required">Description:</label>
                <p class="required">{{detail_error.description}}</p>
                <!-- <input type="text" name="title" value={{detail_error.title}} class="vTextField" maxlength="225" id="id_title"> -->
            </div>
        
            
            {% if detail_error.status %}
                <div  style="padding-left:100px; padding-right:100px;" >
                    <label class="required" for="id_title">Solution code:</label>
                    <pre class="prettyprint" class="required" for="id_title">{{detail_solution.solution_code}}</pre>
                </div>
                <div style="padding-left:100px;" >
                    <label class="required" for="id_title">Solution description:</label>
                    <p class="required" for="id_title">{{detail_solution.solution_description}}</p>
                </div>
                <center>
                    <a href="{% url 'index' %}" class="btn btn-lg btn-info">main으로</a>
                </center>
                {% else %}
                <center>
                    <a href="{% url 'logging_solution' detail_error.id %}" class="btn btn-lg btn-info">Solution 기록하기</a>
                </center>
            {% endif %}
        
    </body>
</html>

ErrorSave/error_manage_system/templates/error_manage_system/index.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <meta name="description" content>

        <title>Error Save</title>

        <meta name="author" content>
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>

    <body>
      <center>
          <!-- <form>
              <a href="{% url 'index' %}">
                  <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
              </a>
          </form>           -->
          <form action="./search_title/" method="POST">{% csrf_token %}
            <a href="{% url 'index' %}">
              <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
            </a>
            <input id="errorTitle" name="errorTitle" type="text" placeholder="제목검색 키워드를 입력하세요" style="width:300px;height:50px;font-size:20px;"/>
            <span>
                <button type="submit" class="btn btn-default btn-lg">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
          </form>
          
          <hr/>
          <form  method="POST">  {% csrf_token%}
              <input type="radio" id="all" name="Filter" value="all">
              <label for="all" style="font-size:20px;padding-right: 25px;">All error</label>

              <input type="radio" id="outstanding" name="Filter" value="outstanding">
              <label for="outstanding" style="font-size:20px;padding-right: 25px;">Outstanding error</label>
              
              <input type="radio" id="resolved" name="Filter" value="resolved">
              <label for="resolved" style="font-size:20px;padding-right: 15px;">Resolved error</label>
              
              <button type="submit" class="btn btn-ms btn-info" value="Serch">Serch</button>

          <div class="table-responsive">
              <table class="table table table-hover">
                <thead>
                  <tr>
                    <th>게시자</th>
                    <th>Error 제목</th>
                    <th>Error 메시지</th>
                    <th>해결여부</th>
                    <th>상세 페이지</th>
                  </tr>
                </thead>
                <tbody>
                  {% for error in errors%}
                      {% for match in matchs%}
                        {% if error.id == match.error_id %}
                            {% for user in users %}
                                {% if match.user_id == user.id %}
                                    
                                    {% if error.status == False %}
                                    <tr>
                                        <td>{{user.user_name}}</td>
                                        <td>{{error.title}}</td>
                                        <td>{{error.message}}</td>
                                        <td style="padding-left: 35px;">X</td>
                                        <input type="hidden" id="id" name="id" value="{{ error.id }}">
                                        <td><a href="{% url 'detailError' error.id %}" class="btn btn-success">Detail</a></td>
                                    </tr>
                                  {% else %}
                                    <tr class='info'>
                                      <td>{{user.user_name}}</td>
                                      <td>{{error.title}}</td>
                                      <td>{{error.message}}</td>
                                      <td style="padding-left: 35px;">O</td>
                                      <input type="hidden" id="id" name="id" value="{{ error.id }}">
                                      <td><a href="{% url 'detailError' error.id %}" class="btn btn-success">Detail</a></td>
                                    </tr>
                                  {% endif %}

                                {% endif %}
                            {% endfor %}
                        {% endif %}
                      {% endfor %}
                      
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </form>

          <form>
              <a href="{% url 'logging_error' %}" class="btn btn-lg btn-info">Error 기록하기</a>
              <a href="{% url 'my_error' %}" class="btn btn-lg btn-info">내 에러 보기</a>
          </form>
        </center>
    </body>
</html>

ErrorSave/error_manage_system/templates/error_manage_system/logging_error.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <meta name="description" content>

        <title>Error Save</title>

        <meta name="author" content>
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        
        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    </head>

    <body>
        <a href="{% url 'index' %}">
            <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
        </a><br><br><br>


        <form action="./createError/" method="POST">{% csrf_token %}
            <center>
                <div style="padding-left:100px;">
                <input name="title" type="text" placeholder="에러 제목" style="width:700px;height:50px;font-size:20px;"/>                    
                </div>
                <br>
                <div style="padding-left:100px;">
                    <textarea name="message" cols="40" rows="2" placeholder="에러 메시지" style="width:700px;height:50px;font-size:20px;"></textarea>
                </div>
                <br>
                <div style="padding-left:100px;">
                    <textarea name="code" cols="40" rows="10" placeholder="에러 코드" style="width:700px;height:200px;font-size:20px;"></textarea>
                </div>
                    <br>
                <div style="padding-left:100px;">
                    <textarea name="description" cols="40" rows="10" placeholder="메모" style="width:700px;height:50px;font-size:20px;"></textarea>
                </div>
            </center>
            <form style="padding-left:100px;">
                <br><br>
                <center>
                    <button type="submit" class="btn btn-lg btn-info">에러 올리기</button>
                    <a href="{% url 'index' %}" class="btn btn-default btn-lg">취소하기</a>
                </center>
            </form>
        </form>

    </body>
</html>

ErrorSave/error_manage_system/templates/error_manage_system/logging_solution.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <meta name="description" content>

        <title>Error Save</title>

        <meta name="author" content>
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        
        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    </head>

    <body>
        <a href="{% url 'index' %}">
            <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
        </a><br><br><br>


        <form action="./createSolution/" method="POST">{% csrf_token %}
            <center>
                <div style="padding-left:100px;">
                    <textarea name="solution_code" cols="40" rows="10" placeholder="해결 코드" style="width:700px;height:200px;font-size:20px;"></textarea>
                </div>
                    <br>
                <div style="padding-left:100px;">
                    <textarea name="solution_description" cols="40" rows="2" placeholder="메모" style="width:700px;height:50px;font-size:20px;"></textarea>
                </div>
            </center>
            <form style="padding-left:100px;">
                <br><br>
                <center>
                    <button type="submit" class="btn btn-lg btn-info">solution 올리기</button>
                    <a href="{% url 'detailError' match_error.id %}" class="btn btn-default btn-lg">취소하기</a>
                </center>
            </form>
        </form>

    </body>
</html>

ErrorSave/error_manage_system/templates/error_manage_system/my_detail_error.html
{% load static %}
<!DOCTYPE>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
        <meta name="description" content>

        <title>Error Save</title>

        <meta name="author" content>
        <!-- jquery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

        <!-- 부트스트랩 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </head>

    <body>

            <a href="{% url 'index' %}">
                <img src="{% static 'img/logo.jpg' %}" alt="main page" height="75" width="320">
            </a>

            
            <form action="./updateError/" method="POST">{% csrf_token %}
                
                <input type="hidden" id="id" name="id" value="{{detail_error.id}}">
                <div style="padding-left:100px;">
                    <label class="required">Title:</label>
                    <br>
                    <input name="title" type="text" value="{{detail_error.title}}"  style="width:700px;height:20px;font-size:15px;"/>                    
                    <!-- <p class="required">{{detail_error.title}}</p> -->
                    <!-- <input type="text" name="title" value={{detail_error.title}} class="vTextField" maxlength="225" id="id_title"> -->
                </div>

                <div style="padding-left:100px; padding-right:100px;" >
                    <label class="required" for="id_title">Message:</label>
                    <br>
                    <textarea name="message" cols="40" rows="2" style="width:700px;height:25px;font-size:15px;">{{detail_error.message}}</textarea>
                </div>

                <div style="padding-left:100px; padding-right:100px;">
                    <label class="required" for="id_title">Code:</label>
                    <br>
                    <textarea name="code" cols="10" rows="10" style="width:700px;font-size:15px;">{{detail_error.code}}</textarea>
                </div>

                <div style="padding-left:100px;" >
                    <label class="required">Description:</label>
                    <br>
                    <textarea name="description" cols="40" rows="10" style="width:700px;height:25px;font-size:15px;">{{detail_error.description}}</textarea>
                </div>
        
           
            
            {% if detail_error.status %}
<!-- -------------------------------------------------------------------------------------------------------- -->
                <input type="hidden" id="solution_status" name="solution_status" value="1">
                <div style="padding-left:100px; padding-right:100px;">
                    <label class="required" for="id_title">Solution code:</label>
                    <br>
                    <textarea name="sol_code" cols="10" rows="10" style="width:700px;font-size:15px;">{{detail_solution.solution_code}}</textarea>
                </div>

                <div style="padding-left:100px;" >
                    <label class="required">Solution description:</label>
                    <br>
                    <textarea name="sol_description" cols="40" rows="10" style="width:700px;height:25px;font-size:15px;">{{detail_solution.solution_description}}</textarea>
                </div>

<!-- -------------------------------------------------------------------------------------------------------- -->
                <!-- <div  style="padding-left:100px; padding-right:100px;" >
                    <label class="required" for="id_title">Solution code:</label>

                    <pre class="prettyprint" class="required" for="id_title">{{detail_solution.solution_code}}</pre>
                </div>
                <div style="padding-left:100px;" >
                    <label class="required" for="id_title">Solution description:</label>

                    <p class="required" for="id_title">{{detail_solution.solution_description}}</p>
                </div>
 -->
<!-- -------------------------------------------------------------------------------------------------------- -->
                <div style="padding-left:100px;" >
                    <br>
                    <button type="submit" class="btn btn-lg btn-success">수정하기</button>
                    <a href="{% url 'index' %}" class="btn btn-lg btn-info">main으로</a>
                </div>


                {% else %}
                <input type="hidden" id="solution_status" name="solution_status" value="0">
                <br>
                <div style="padding-left:100px;" >
                    <button type="submit" class="btn btn-lg btn-success">수정하기</button>
                    <a href="{% url 'logging_solution' detail_error.id %}" class="btn btn-lg btn-info">Solution 기록하기</a>
                </div>
            {% endif %}
        </form>
    </body>
</html>